require('dotenv').config();
const image = (id, width = 1000) => id.startsWith('https://') ? id : `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=84`;
const T = 'photo-1609766857041-ed402ea8069a', F = 'photo-1548013146-72479768bada', C = 'photo-1577083552431-6e5fd01aa342', D = 'photo-1514525253161-7a46d19cd819', S = 'photo-1547592180-85f173990554', W = 'photo-1610030469983-98e550d6193c';
const make = (base) => {
  const rows = (values, keys) => values.map(([name, description, imageId, extra = {}]) => ({ [keys[0]]: name, [keys[1]]: description, imageUrl: image(imageId), ...extra }));
  const templesAndBeliefs = base.temples.map(([name, story, imageId]) => ({ name, story, belief: 'A living practice connecting community, memory, and place.', imageUrl: image(imageId) }));
  const foodAndCuisine = base.food.map(([dishName, description, imageId]) => ({ dishName, description, vendorTrail: base.foodTrail, imageUrl: image(imageId) }));
  const folkDanceAndMusic = base.dance.map(([formName, description, imageId]) => ({ formName, category: 'Folk tradition', instruments: base.instruments, description, imageUrl: image(imageId) }));
  const folkArtAndAttire = base.art.map(([artName, craftsmanship, imageId]) => ({ artName, attireType: base.attire, craftsmanship, imageUrl: image(imageId) }));
  const historyAndHeritage = base.history.map(([siteName, historicalContext, imageId]) => ({ siteName, historicalContext, imageUrl: image(imageId) }));
  return { ...base, heroImage: image(base.heroImage, 1800), templesAndBeliefs, foodAndCuisine, folkDanceAndMusic, folkArtAndAttire, historyAndHeritage, languages: { primary: base.language, phrases: base.phrases, etiquette: base.etiquette }, gallery: [base.heroImage, ...base.temples, ...base.food, ...base.dance, ...base.art, ...base.history].map((item) => image(Array.isArray(item) ? item[2] : item, 1200)) };
};
const common = (id, name, state, tagline, heroImage, language, foodTrail, instruments, attire, temples, food, dance, art, history, phrases, etiquette, badges = []) => ({ id, name, state, country: 'India', tagline, heroImage, language, foodTrail, instruments, attire, temples, food, dance, art, history, phrases, etiquette, badges, rating: 4.8 });

const pilotData = [
  common('agra', 'Agra', 'Uttar Pradesh', 'Mughal grandeur, marble craft, and Braj heritage', 'photo-1564507592333-c60657eea523', 'Hindi / Braj Bhasha', 'Sadar Bazaar and Kinari Bazaar food lanes', 'Tabla, shehnai, and sarangi', 'Braj cottons and Mughal-inspired embroidery', [['Taj Mahal', 'A monument to love and masterful symmetry.', 'photo-1564507592333-c60657eea523'], ['Agra Fort', 'A red sandstone citadel shaped by Mughal emperors.', 'photo-1585135497273-1a86b09fe70e'], ['Fatehpur Sikri', 'An imperial city where red sandstone meets Sufi memory.', 'photo-1599661046289-e31897846e41']], [['Agra Petha', 'A rose-scented ash-gourd sweet.', 'photo-1551024601-bec78aea704b'], ['Bedai & Jalebi', 'Crisp spiced bread and syrupy coils.', 'photo-1601050690597-df0568f70950'], ['Mughlai Paratha', 'Layered flatbread from courtly kitchens.', 'photo-1565299624946-b28f40a0ae38']], [['Braj Rasleela', 'Devotional theatre from the Braj region.', D], ['Kathak', 'Storytelling dance shaped by rhythm and gesture.', 'photo-1518002171953-a080ee817e1f']], [['Marble Inlay / Pietra Dura', 'Semi-precious stone set into marble.', C], ['Zardozi Embroidery', 'Metal thread embroidery with Mughal roots.', 'photo-1599643478518-a784e5dc4c8f']], [['Taj Mahal', 'A Mughal mausoleum and UNESCO World Heritage site.', 'photo-1564507592333-c60657eea523'], ['Agra Fort', 'A fortified palace city at the centre of Mughal power.', 'photo-1585135497273-1a86b09fe70e'], ['Fatehpur Sikri', 'Akbar’s planned capital and UNESCO site.', 'photo-1599661046289-e31897846e41']], [{ original: 'Namaste', phonetic: 'na-mas-te', translation: 'Hello', note: 'A respectful greeting.' }], ['Dress modestly at monuments and shrines', 'Ask before photographing artisans'], ['Mughal legacy', 'Marble inlay', 'Braj cuisine']),
  common('kolkata', 'Kolkata', 'West Bengal', 'Colonial avenues, river memory, and Bengal’s creative soul', 'photo-1558431382-27e303142255', 'Bengali / Hindi', 'New Market, Park Street, and Kumartuli lanes', 'Tabla, esraj, and khol', 'Jamdani sarees and Bengali cottons', [['Dakshineswar Kali Temple', 'A riverside Kali temple and pilgrimage site.', T], ['Kalighat Temple', 'A living Shakti shrine in south Kolkata.', F]], [['Mishti Doi', 'Caramelised sweet yoghurt in earthen pots.', 'photo-1488477181946-6428a0291777'], ['Rosogolla', 'Soft chhena dumplings in sugar syrup.', 'photo-1551024506-0bccd828d307'], ['Kolkata Kathi Rolls', 'Paratha wrapped around spiced fillings.', 'photo-1565299507177-b0ac66763828'], ['Machher Jhol', 'Light Bengali fish curry with mustard and greens.', S]], [['Rabindra Sangeet', 'Poetry and melody inspired by Tagore.', 'photo-1511379938547-c1f69419868d'], ['Baul Folk Music', 'Mystic travelling singers and ecstatic song.', 'photo-1516280440614-37939bbacd81'], ['Chhau Dance', 'Masked martial dance from eastern India.', D]], [['Terracotta Pottery', 'Bengal clay craft for ritual and daily life.', 'photo-1493106641515-6b5631de4bb9'], ['Jamdani Sarees', 'Fine muslin weaving with floral motifs.', W], ['Kumartuli Idol Crafting', 'Clay sculptors build Durga Puja images.', C]], [['Victoria Memorial', 'Marble museum and garden of colonial Kolkata.', 'photo-1558431382-27e303142255'], ['Howrah Bridge', 'Working cantilever landmark over the Hooghly.', F], ['Dakshineswar Kali Temple', 'A nineteenth-century temple on the Ganga.', T]], [{ original: 'Nomoshkar', phonetic: 'no-mosh-kar', translation: 'Hello', note: 'A courteous Bengali greeting.' }], ['Remove shoes in temples', 'Ask before photographing rituals'], ['Bengali culture', 'Durga Puja', 'Literary city']),
  common('amritsar', 'Amritsar', 'Punjab', 'Golden light, generous kitchens, and dhol rhythms', 'photo-1582510003544-4d00b7f74220', 'Punjabi / Hindi', 'Hall Bazaar and old city dhaba trail', 'Dhol, algoza, and tumbi', 'Phulkari dupattas and Punjabi juttis', [['Sri Harmandir Sahib / Golden Temple', 'A sacred pool, luminous shrine, and open langar.', 'photo-1582510003544-4d00b7f74220'], ['Durgiana Temple', 'Historic temple complex with a sacred tank.', F]], [['Amritsari Kulcha', 'Tandoor-baked stuffed bread with chole.', 'photo-1601050690597-df0568f70950'], ['Butter Lassi', 'Thick yoghurt drink and Punjabi welcome.', 'photo-1488477181946-6428a0291777'], ['Dal Makhani', 'Slow-cooked black lentils with butter.', S]], [['Bhangra', 'High-energy harvest dance powered by dhol.', D], ['Giddha', 'Women’s folk dance of verses and gesture.', 'photo-1506157786151-b8491531f063'], ['Dhol Performance', 'The drumbeat that brings festivals into motion.', 'photo-1516280440614-37939bbacd81']], [['Phulkari Embroidery', 'Silk floss turns shawls into family memory.', W], ['Punjabi Juttis', 'Hand-stitched leather footwear with mirror work.', 'photo-1542291026-7eec264c27ff']], [['Sri Harmandir Sahib', 'A spiritual centre of Sikh heritage and langar.', 'photo-1582510003544-4d00b7f74220'], ['Jallianwala Bagh', 'Memorial garden carrying freedom-struggle memory.', F], ['Wagah Border', 'Daily ceremony framed by music and flags.', 'photo-1500534623283-312aade485b7']], [{ original: 'Sat Sri Akal', phonetic: 'sat sree akaal', translation: 'Respectful hello', note: 'A warm Punjabi greeting.' }], ['Cover your head inside the Golden Temple', 'Wash hands before joining langar'], ['Langar tradition', 'Bhangra spirit', 'Phulkari']),
  common('udaipur', 'Udaipur', 'Rajasthan', 'Lakes, Mewar miniatures, and palace stories', 'photo-1477587458883-47145ed94245', 'Hindi / Mewari', 'Hathi Pol market and lakefront kitchens', 'Ravanahatha, dholak, and algoza', 'Bandhani odhnis and Rajput ceremonial dress', [['Jagdish Temple', 'Grand Vishnu temple above old city lanes.', T], ['Eklingji Temple', 'Revered Shiva complex in the Aravallis.', F]], [['Dal Baati Churma', 'Rajasthan’s iconic wheat, lentil, and sweet meal.', 'photo-1601050690597-df0568f70950'], ['Gatte ki Sabzi', 'Gram-flour dumplings in spiced yoghurt.', S], ['Ker Sangri', 'Desert beans and berries in bold masala.', 'photo-1565299624946-b28f40a0ae38']], [['Ghoomar', 'Circular dance with sweeping skirts.', 'photo-1518002171953-a080ee817e1f'], ['Kalbelia Snake Dance', 'Sinuous desert dance of the Kalbelia community.', D], ['Ravanahatha Music', 'Bowed string tradition of storytellers.', 'photo-1511379938547-c1f69419868d']], [['Mewar Miniature Paintings', 'Fine brushwork of court and monsoon.', C], ['Bandhani Tie-Dye', 'Tiny knots create vivid cloth patterns.', W]], [['City Palace', 'Layered palace complex over Lake Pichola.', 'photo-1477587458883-47145ed94245'], ['Lake Pichola', 'A lake holding the city’s reflections.', 'photo-1500534623283-312aade485b7'], ['Jag Mandir', 'Island palace used as royal retreat.', F], ['Saheliyon-ki-Bari', 'Fountain garden made for royal companions.', T]], [{ original: 'Khamma Ghani', phonetic: 'kham-ma gha-nee', translation: 'Respectful hello', note: 'A gracious Mewari greeting.' }], ['Ask before photographing performers', 'Dress thoughtfully at palace sites'], ['Mewar heritage', 'Lake city', 'Miniature art']),
  common('hyderabad', 'Hyderabad', 'Telangana', 'Deccan grandeur, pearl craft, and slow-cooked spice', 'photo-1589177900156-2c7e4c8aa0d1', 'Telugu / Urdu / Hindi', 'Charminar, Laad Bazaar, and Old City kitchens', 'Harmonium, tabla, and dhol', 'Hyderabadi khada dupatta and Deccan textiles', [['Birla Mandir', 'White-marble hilltop temple above the city.', T], ['Mecca Masjid', 'One of Hyderabad’s oldest monumental mosques.', F]], [['Hyderabadi Dum Biryani', 'Layered rice sealed with saffron and spice.', 'photo-1563379091339-03246963d51a'], ['Double Ka Meetha', 'Bread pudding with cardamom and sweet milk.', 'photo-1488477181946-6428a0291777'], ['Haleem', 'Slow-cooked porridge central to Ramadan culture.', S]], [['Qawwali Heritage', 'Devotional music of voice and clapping rhythm.', 'photo-1511379938547-c1f69419868d'], ['Deccani Folk Performance', 'Stories of the plateau through music and movement.', D]], [['Bidriware Metalwork', 'Dark metal inlaid with silver.', C], ['Hyderabad Pearl Craft', 'Pearls shaped into jewellery in old markets.', 'photo-1535632066927-ab7c9ab60908']], [['Charminar', 'Four-minaret emblem of the old city.', 'photo-1589177900156-2c7e4c8aa0d1'], ['Golconda Fort', 'Hill fort famed for acoustics and Qutb Shahi history.', 'photo-1599661046289-e31897846e41'], ['Ramoji Film City', 'Studio complex where regional cinema becomes an experience.', 'photo-1485846234645-a62644f84728'], ['Birla Mandir', 'Modern temple landmark in white marble.', T]], [{ original: 'Namaskaram', phonetic: 'na-mas-ka-ram', translation: 'Hello', note: 'A polite Telugu greeting.' }], ['Dress modestly at religious sites', 'Ask before photographing worshippers'], ['Deccan history', 'Biryani culture', 'Pearl craft']),
  common('mysuru-bengaluru', 'Mysuru & Bengaluru', 'Karnataka', 'Palaces, gardens, coffee, and living performance', 'photo-1600100397608-f010f8f8f4c8', 'Kannada / English', 'Devaraja Market and Bengaluru breakfast trails', 'Chenda, mridangam, and traditional drums', 'Mysore silk sarees and Karnataka cottons', [['Chamundeshwari Temple', 'Hilltop shrine overlooking Mysuru.', T], ['Bull Temple', 'Historic Bengaluru shrine centred on Nandi.', F]], [['Mysore Pak', 'Ghee-rich sweet with a melt-in-the-mouth texture.', 'photo-1551024601-bec78aea704b'], ['Masala Dosa', 'Crisp fermented crepe with spiced potato.', 'photo-1565299624946-b28f40a0ae38'], ['Bisi Bele Bath', 'Rice, lentils, vegetables, and spice.', S], ['Filter Coffee', 'Dark roast with frothy milk.', 'photo-1495474472287-4d71bcdd2085']], [['Yakshagana', 'All-night theatre of dance, music, and epics.', D], ['Dollu Kunitha', 'Powerful group drum dance from Karnataka.', 'photo-1516280440614-37939bbacd81']], [['Mysore Silk Sarees', 'Fine silk and gold zari for ceremony.', W], ['Sandalwood Carving', 'Fragrant wood carved into devotional forms.', C]], [['Mysore Palace', 'Illuminated Indo-Saracenic royal palace.', 'photo-1600100397608-f010f8f8f4c8'], ['Lalbagh', 'Historic botanical garden shaped by royal horticulture.', 'photo-1441974231531-c6227db76b6e'], ['Hampi Heritage Gateway', 'Gateway to Vijayanagara’s monumental landscape.', F]], [{ original: 'Namaskara', phonetic: 'na-mas-ka-ra', translation: 'Hello', note: 'A respectful Kannada greeting.' }], ['Remove footwear at temples', 'Keep heritage gardens clean'], ['Mysore silk', 'Garden city', 'Yakshagana']),
  common('delhi', 'Delhi', 'NCR', 'Empire, memory, and a food trail through old lanes', 'photo-1587474260584-136574528ed5', 'Hindi / Urdu / English', 'Chandni Chowk and Old Delhi food trail', 'Tabla, sarangi, and harmonium', 'Delhi’s mixed textile and zardozi traditions', [['Akshardham', 'Contemporary temple complex celebrating Indian architecture.', T], ['Lotus Temple', 'Modern house of worship open to quiet reflection.', F]], [['Chandni Chowk Food Trail', 'Paratha, chaat, jalebi, and kebabs across Old Delhi.', 'photo-1601050690597-df0568f70950'], ['Nihari', 'Slow-cooked stew of early morning kitchens.', S], ['Daulat ki Chaat', 'Seasonal cloud-like winter sweet.', 'photo-1488477181946-6428a0291777']], [['Kathak', 'North Indian storytelling dance with precise footwork.', 'photo-1518002171953-a080ee817e1f'], ['Sufi Qawwali', 'Devotional performance rooted in shrine culture.', 'photo-1511379938547-c1f69419868d']], [['Zardozi Craft', 'Gold and silver thread embroidery with court origins.', 'photo-1599643478518-a784e5dc4c8f'], ['Dilli Haat Handicrafts', 'Marketplace for crafts from across India.', C]], [['Red Fort', 'Mughal sandstone citadel and independence-day landmark.', 'photo-1587474260584-136574528ed5'], ['Humayun’s Tomb', 'Garden tomb influencing Mughal architecture.', F], ['Akshardham', 'Contemporary cultural and devotional landmark.', T]], [{ original: 'Adaab', phonetic: 'a-daab', translation: 'Respectful greeting', note: 'A graceful Delhi greeting.' }], ['Keep voices low at memorials', 'Ask before photographing street vendors'], ['Layered capitals', 'Old Delhi food', 'Living craft']),
  common('mumbai', 'Mumbai', 'Maharashtra', 'Sea-facing icons, devotional streets, and everyday theatre', 'photo-1529253355930-ddbe423a2ac7', 'Marathi / Hindi / English', 'Dadar, Girgaum, and street-side snack trails', 'Dholki, lezim, and harmonium', 'Nauvari sarees and Maharashtrian festive dress', [['Siddhivinayak Temple', 'Beloved Ganesh temple woven into the daily commute.', T], ['Mumbadevi Temple', 'Old city shrine that gives Mumbai its name.', F]], [['Vada Pav', 'Spiced potato fritter in a bun with chutneys.', 'photo-1601050690597-df0568f70950'], ['Misal Pav', 'Sprouted lentils, farsan, and gravy with bread.', S]], [['Lavani', 'Percussive Marathi dance of rhythm and storytelling.', D], ['Powada Singing', 'Ballad tradition celebrating heroes and memory.', 'photo-1511379938547-c1f69419868d']], [['Warli Art', 'Minimal white figures map farming and ritual.', C], ['Kolhapuri Craft', 'Leather, metal, and ornament traditions.', 'photo-1493106641515-6b5631de4bb9']], [['Gateway of India', 'Seafront arch marking port and colonial history.', 'photo-1529253355930-ddbe423a2ac7'], ['Chhatrapati Shivaji Maharaj Terminus', 'Gothic railway landmark alive with daily movement.', F]], [{ original: 'Namaskar', phonetic: 'na-mas-kar', translation: 'Hello', note: 'A polite Marathi greeting.' }], ['Respect temple queues', 'Avoid blocking busy footpaths'], ['Coastal city', 'Lavani rhythm', 'Warli lines']),
  common('goa', 'Goa', 'Goa', 'Basilica, Shanta Durga, coastal food, and tile craft', 'photo-1512343879784-a960bf40e7f2', 'Konkani / English', 'Panaji, Mapusa, and Old Goa food lanes', 'Ghumot, mando guitar, and dhol', 'Kazar and Kunbi textiles', [['Shanta Durga Temple', 'Peaceful temple complex with Goan architecture.', T], ['Basilica of Bom Jesus', 'Baroque church and Old Goa heritage site.', F]], [['Goan Fish Curry', 'Coconut, kokum, and coastal spice.', S], ['Bebinca', 'Layered coconut dessert baked slowly.', 'photo-1488477181946-6428a0291777']], [['Fugdi', 'Women’s circle dance of festivals and gatherings.', D], ['Mando Music', 'Goan song tradition of romance and memory.', 'photo-1511379938547-c1f69419868d']], [['Azulejos Tile Craft', 'Painted ceramic tilework shaped by colonial architecture.', C], ['Coconut Craft', 'Coastal material transformed into practical objects.', 'photo-1577083552431-6e5fd01aa342']], [['Basilica of Bom Jesus', 'Old Goa Baroque heritage and pilgrimage landmark.', F], ['Fort Aguada', 'Coastal fort and lighthouse at Goa’s maritime entrance.', 'photo-1512343879784-a960bf40e7f2']], [{ original: 'Dev borem korum', phonetic: 'dev bor-em kor-um', translation: 'Thank you', note: 'A warm Konkani expression.' }], ['Dress respectfully at churches and temples', 'Leave beaches clean'], ['Coastal heritage', 'Colonial memory', 'Konkan food']),
  common('mathura-vrindavan', 'Mathura & Vrindavan', 'Uttar Pradesh', 'Shri Krishna Janmabhoomi, Braj Rasleela, and festival color', 'photo-1599661046289-e31897846e41', 'Hindi / Braj Bhasha', 'Brijwasi Sweets and Banke Bihari lanes', 'Flute, pakhawaj, and manjira', 'Bright ghagra-choli, odhnis, and temple textiles', [['Shri Krishna Janmabhoomi', 'Pilgrimage centre associated with Krishna’s birthplace.', T], ['Banke Bihari Temple', 'Beloved Vrindavan temple of intimate darshan.', F]], [['Mathura Peda', 'Milk-based sweet shared across Braj.', 'photo-1551024601-bec78aea704b'], ['Kachori Sabzi', 'Spiced breakfast in old city lanes.', 'photo-1601050690597-df0568f70950']], [['Braj Rasleela', 'Krishna’s stories become theatre and dance.', D], ['Rasiya Singing', 'Braj folk songs of devotion and seasons.', 'photo-1511379938547-c1f69419868d']], [['Sanjhi Art', 'Delicate paper stencil work inspired by Vrindavan.', C]], [['Shri Krishna Janmabhoomi', 'Sacred site central to Braj tradition.', T], ['Govardhan Hill', 'Pilgrimage landscape walked in parikrama.', F]], [{ original: 'Radhe Radhe', phonetic: 'raa-dhey raa-dhey', translation: 'Devotional greeting', note: 'Beloved across Braj.' }], ['Dress modestly in temple areas', 'Ask before photographing worshippers'], ['Krishna devotion', 'Braj culture', 'Holi traditions']),
  common('ayodhya', 'Ayodhya', 'Uttar Pradesh', 'Shri Ram Janmabhoomi, Saryu heritage, and living epic', 'photo-1606298855672-3efb63017be8', 'Hindi / Awadhi', 'Ram ki Paidi and Kanak Bhawan food lanes', 'Dholak, harmonium, and manjira', 'Festive kurtas, saris, and regional odhnis', [['Shri Ram Janmabhoomi Mandir', 'Major contemporary pilgrimage destination.', T], ['Hanuman Garhi', 'Hilltop temple reached by celebrated steps.', F]], [['Ram Ladoo', 'Crisp lentil fritters with chutney.', 'photo-1601050690597-df0568f70950'], ['Malai Peda', 'Soft milk sweet around temple markets.', 'photo-1551024601-bec78aea704b']], [['Ram Leela Theatre', 'Ramayana performed through dialogue and music.', D], ['Awadhi Devotional Song', 'Bhajan traditions along the Saryu.', 'photo-1511379938547-c1f69419868d']], [['Ramayana Painting', 'Handmade visual storytelling from epic scenes.', C]], [['Shri Ram Janmabhoomi Mandir', 'Central contemporary pilgrimage landmark.', T], ['Saryu Ghat', 'Riverfront rituals make the river living heritage.', F]], [{ original: 'Jai Shri Ram', phonetic: 'jai shree raam', translation: 'Victory to Lord Ram', note: 'Use respectfully.' }], ['Follow temple photography rules', 'Dress modestly near sacred sites'], ['Ramayana traditions', 'Saryu ghats', 'Deepotsav']),
  common('uttarakhand', 'Uttarakhand', 'Uttarakhand', 'Haridwar, Rishikesh, Char Dham temples, and Ganges heritage', 'photo-1548013146-72479768bada', 'Hindi / Garhwali / Kumaoni', 'Haridwar bazaar and Rishikesh ashram kitchens', 'Dhol damau, ransingha, and flute', 'Wool shawls, pichora textiles, and mountain dress', [['Har Ki Pauri', 'Sacred riverfront and evening Ganga Aarti.', F], ['Badrinath', 'Char Dham temple in the Himalayan landscape.', T], ['Kedarnath', 'Mountain pilgrimage site and seasonal journey.', 'photo-1512343879784-a960bf40e7f2']], [['Aloo ke Gutke', 'Mountain potatoes with local herbs.', S], ['Bal Mithai', 'Brown milk fudge with sugar pearls.', 'photo-1551024601-bec78aea704b']], [['Choliya Dance', 'Kumaoni sword dance at ceremonies.', D], ['Langvir Nritya', 'Acrobatic performance carried by mountain rhythm.', 'photo-1511379938547-c1f69419868d']], [['Aipan Painting', 'Ritual designs made with rice paste.', C]], [['Har Ki Pauri', 'Riverfront where pilgrimage and ecology meet.', F], ['Badrinath', 'One of the Char Dham temples.', T], ['Kedarnath', 'Himalayan shrine on a historic route.', 'photo-1512343879784-a960bf40e7f2']], [{ original: 'Jai Badri Vishal', phonetic: 'jai bad-ree vish-aal', translation: 'Devotional greeting', note: 'Used respectfully in Badrinath tradition.' }], ['Avoid litter near rivers and temples', 'Ask before photographing rituals'], ['Devbhoomi', 'Ganga heritage', 'Mountain temples']),
  common('madurai-tanjore', 'Madurai & Tanjore', 'Tamil Nadu', 'Dravidian temples, Tanjore painting, and Bharatanatyam rhythm', 'photo-1582510003544-4d00b7f74220', 'Tamil', 'Madurai night markets and Tanjore temple streets', 'Nadaswaram, mridangam, and thavil', 'Kanchipuram silk saris and veshtis', [['Meenakshi Amman Temple', 'Monumental temple city alive with ritual and sculpture.', T], ['Brihadeeswarar Temple', 'Chola masterpiece of engineering and devotion.', F]], [['Jigarthanda', 'Cooling Madurai drink of milk and almond gum.', 'photo-1488477181946-6428a0291777'], ['Thanjavur Thali', 'Banana-leaf meal of the Kaveri delta.', S]], [['Bharatanatyam', 'Gesture and rhythm transform temple sculpture into movement.', 'photo-1518002171953-a080ee817e1f'], ['Nadaswaram Performance', 'Temple wind music with a bright sound.', 'photo-1511379938547-c1f69419868d']], [['Tanjore Painting', 'Gold foil and devotional iconography on wood.', C], ['Chola Bronze Casting', 'Lost-wax bronze sculpture with ritual presence.', 'photo-1493106641515-6b5631de4bb9']], [['Meenakshi Amman Temple', 'Living Dravidian temple complex at Madurai.', T], ['Brihadeeswarar Temple', 'UNESCO-listed Chola landmark at Tanjore.', F]], [{ original: 'Vanakkam', phonetic: 'va-na-kkam', translation: 'Hello', note: 'A gracious Tamil greeting.' }], ['Remove footwear in temples', 'Dress shoulders and knees modestly'], ['Dravidian temples', 'Bharatanatyam', 'Chola art']),
  common('jaipur', 'Jaipur', 'Rajasthan', 'Hawa Mahal, Amer Fort, and the craft of the Pink City', 'photo-1477587458883-47145ed94245', 'Hindi / Rajasthani', 'Johari Bazaar and old city thali trails', 'Ravanhatha, dholak, and algoza', 'Lehenga choli, odhnis, and Safa turbans', [['Govind Dev Ji Temple', 'Major Vaishnav temple inside Jaipur’s royal city.', T], ['Moti Dungri Ganesh Temple', 'Hilltop shrine woven into daily Jaipur.', F]], [['Dal Baati Churma', 'Baked wheat, lentils, and sweet crumble.', 'photo-1601050690597-df0568f70950'], ['Ghevar', 'Honeycomb festival sweet soaked with syrup.', 'photo-1551024601-bec78aea704b']], [['Ghoomar', 'Swirling dance with sweeping skirts.', 'photo-1518002171953-a080ee817e1f'], ['Kalbelia', 'Sinuous desert dance of Kalbelia community.', D]], [['Blue Pottery', 'Glazed floral pottery made without traditional clay.', C], ['Block Printing', 'Carved blocks and natural dyes make patterned cloth.', W]], [['Hawa Mahal', 'Iconic pink facade for royal observation of city life.', 'photo-1477587458883-47145ed94245'], ['Amer Fort', 'Hill fort of mirror halls and Rajput-Mughal history.', 'photo-1599661046289-e31897846e41']], [{ original: 'Khamma Ghani', phonetic: 'kham-ma gha-nee', translation: 'Respectful hello', note: 'A gracious greeting.' }], ['Remove shoes at temples', 'Ask before photographing artisans'], ['Pink City', 'Amer Fort', 'Blue pottery']),
  common('varanasi', 'Varanasi', 'Uttar Pradesh', 'Kashi Vishwanath, Dashashwamedh Ghat, and Banarasi silk', 'photo-1561361058-c24cecae35ca', 'Hindi / Bhojpuri', 'Kachori Gali and the ghats’ tea stalls', 'Shehnai, tabla, and sarangi', 'Banarasi silk saris and handloom cottons', [['Kashi Vishwanath', 'Major Shiva temple in Kashi’s spiritual heart.', T], ['Sankat Mochan Temple', 'Hanuman temple known for music and devotion.', F]], [['Malaiyyo', 'Winter milk foam sweet scented with saffron.', 'photo-1488477181946-6428a0291777'], ['Kachori Jalebi', 'Crisp breakfast followed by syrupy sweet.', 'photo-1601050690597-df0568f70950']], [['Chaiti', 'Seasonal folk song tradition of eastern Uttar Pradesh.', 'photo-1511379938547-c1f69419868d'], ['Kajri', 'Monsoon music carried through longing and melody.', 'photo-1516280440614-37939bbacd81']], [['Banarasi Silk', 'Looms turn silk and zari into inherited motifs.', W]], [['Kashi Vishwanath', 'Central sacred landmark of the city.', T], ['Dashashwamedh Ghat', 'Riverfront stage for evening Ganga Aarti.', 'photo-1561361058-c24cecae35ca']], [{ original: 'Namaste', phonetic: 'na-mas-te', translation: 'Hello', note: 'A respectful greeting.' }], ['Dress modestly near temples and ghats', 'Ask before photographing ceremonies'], ['Sacred river', 'Malaiyyo', 'Banarasi silk'])
].map(make);

const requestedImageOverrides = {
  agra: { temples: [['Mankameshwar Temple & Taj Heritage', 'A sacred Agra landmark connecting temple devotion with Mughal memory.', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80']] },
  kolkata: { temples: [['Dakshineswar Kali Temple', 'A riverside temple dedicated to Goddess Kali.', 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80'], ['Kalighat Temple', 'A living Shakti shrine in south Kolkata.', 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80']] },
  amritsar: { temples: [['Sri Harmandir Sahib / Golden Temple', 'A sacred pool, luminous shrine, and open langar.', 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80'], ['Durgiana Temple', 'A historic temple complex with a sacred water tank.', 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=800&q=80']] },
  udaipur: { temples: [['Jagdish Temple', 'A grand Vishnu temple above Udaipur’s old city.', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80'], ['Eklingji Temple', 'A revered Shiva complex in the Aravalli landscape.', 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80']] },
  hyderabad: { heroImage: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80', temples: [['Birla Mandir', 'A white-marble hilltop temple overlooking Hyderabad.', 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=800&q=80'], ['Mecca Masjid', 'One of Hyderabad’s oldest monumental places of worship.', 'https://images.unsplash.com/photo-1589177900156-2c7e4c8aa0d1?auto=format&fit=crop&w=800&q=80']] },
  'mysuru-bengaluru': { heroImage: 'https://images.unsplash.com/photo-1600100397608-f010e423b971?auto=format&fit=crop&w=1200&q=80', temples: [['Chamundeshwari Hill Temple', 'A hilltop shrine overlooking Mysuru.', 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80'], ['Mysore Palace Temple Complex', 'Royal architecture and devotion meet in the palace precinct.', 'https://images.unsplash.com/photo-1600100397608-f010e423b971?auto=format&fit=crop&w=800&q=80']] },
  delhi: { temples: [['Akshardham Temple', 'A contemporary temple complex celebrating Indian architecture.', 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80'], ['Lotus Temple', 'A modern house of worship open to quiet reflection.', 'https://images.unsplash.com/photo-1585135497273-1a86b09fe707?auto=format&fit=crop&w=800&q=80']] },
  mumbai: { temples: [['Siddhivinayak Temple', 'A beloved Ganesh temple woven into the city’s daily life.', 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80'], ['Mumba Devi Mandir', 'The old city shrine that gives Mumbai its name.', 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80']] },
  goa: { temples: [['Shanta Durga & Mangueshi Temple', 'Twin traditions of Goan temple architecture and devotion.', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80']] },
  'mathura-vrindavan': { temples: [['Shri Krishna Janmabhoomi', 'A major pilgrimage centre associated with Krishna’s birthplace.', 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80'], ['Banke Bihari Mandir', 'A beloved Vrindavan temple where darshan is intimate and rhythmic.', 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80'], ['Prem Mandir', 'A luminous temple complex celebrating Braj devotion.', 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=800&q=80']] },
  ayodhya: { temples: [['Shri Ram Janmabhoomi', 'A major contemporary pilgrimage destination.', 'https://images.unsplash.com/photo-1705998188176-b6302e1762e1?auto=format&fit=crop&w=800&q=80'], ['Hanuman Garhi', 'A hilltop temple reached by a celebrated flight of steps.', 'https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80'], ['Saryu River Ghats', 'Riverfront rituals make the Saryu a living heritage space.', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80']] },
  uttarakhand: { temples: [['Kedarnath & Badrinath Dhams', 'Himalayan pilgrimage routes shaped by season and devotion.', 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80'], ['Har Ki Pauri Haridwar', 'A sacred riverfront and evening Ganga Aarti.', 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80']] },
  'madurai-tanjore': { temples: [['Meenakshi Amman Temple', 'A monumental temple city alive with ritual and sculpture.', 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=800&q=80'], ['Brihadeeswarar Temple', 'A Chola masterpiece of engineering, devotion, and stone.', 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80']] },
  jaipur: { temples: [['Govind Dev Ji Temple', 'A major Vaishnav temple inside Jaipur’s royal city.', 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=800&q=80'], ['Galtaji Monkey Temple', 'A historic temple complex in the Aravalli hills.', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80']] },
  varanasi: { temples: [['Kashi Vishwanath Mandir', 'A major Shiva temple in Kashi’s spiritual heart.', 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80'], ['Dashashwamedh Ghat Ganga Aarti', 'The riverfront stage for evening Ganga Aarti.', 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80']] },
};

Object.entries(requestedImageOverrides).forEach(([id, overrides]) => {
  const destination = pilotData.find((item) => item.id === id);
  if (!destination) return;
  if (overrides.heroImage) destination.heroImage = overrides.heroImage;
  destination.templesAndBeliefs = overrides.temples.map(([name, story, imageUrl]) => ({ name, story, belief: 'A living practice connecting community, memory, and place.', imageUrl, badge: 'Sacred place' }));
  destination.gallery.unshift(...destination.templesAndBeliefs.map((item) => item.imageUrl));
});

module.exports = pilotData;

if (require.main === module && (process.env.MONGO_URI || process.env.MONGODB_URI)) {
  const mongoose = require('mongoose');
  const Destination = require('./models/Destination');
  mongoose.connect(process.env.MONGO_URI || process.env.MONGODB_URI).then(async () => {
    await Destination.deleteMany({});
    await Destination.insertMany(pilotData);
    console.log(`Seeded ${pilotData.length} image-rich Indian destinations.`);
    await mongoose.disconnect();
  }).catch((error) => { console.error('MongoDB seed failed:', error.message); process.exitCode = 1; });
}
